//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/ThrowableInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ThrowableInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ThrowableInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ThrowableInputs"",
    ""maps"": [
        {
            ""name"": ""RemoteBomb"",
            ""id"": ""161f2dcf-4509-40ca-99fe-51be1a9cf5c6"",
            ""actions"": [
                {
                    ""name"": ""Detonate"",
                    ""type"": ""Button"",
                    ""id"": ""afa4753d-a111-4a1c-b59c-13af30bb8181"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c5efad20-10a1-4692-a6cc-a64484e1d0ba"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Detonate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RemoteBomb
        m_RemoteBomb = asset.FindActionMap("RemoteBomb", throwIfNotFound: true);
        m_RemoteBomb_Detonate = m_RemoteBomb.FindAction("Detonate", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RemoteBomb
    private readonly InputActionMap m_RemoteBomb;
    private IRemoteBombActions m_RemoteBombActionsCallbackInterface;
    private readonly InputAction m_RemoteBomb_Detonate;
    public struct RemoteBombActions
    {
        private @ThrowableInputs m_Wrapper;
        public RemoteBombActions(@ThrowableInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Detonate => m_Wrapper.m_RemoteBomb_Detonate;
        public InputActionMap Get() { return m_Wrapper.m_RemoteBomb; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RemoteBombActions set) { return set.Get(); }
        public void SetCallbacks(IRemoteBombActions instance)
        {
            if (m_Wrapper.m_RemoteBombActionsCallbackInterface != null)
            {
                @Detonate.started -= m_Wrapper.m_RemoteBombActionsCallbackInterface.OnDetonate;
                @Detonate.performed -= m_Wrapper.m_RemoteBombActionsCallbackInterface.OnDetonate;
                @Detonate.canceled -= m_Wrapper.m_RemoteBombActionsCallbackInterface.OnDetonate;
            }
            m_Wrapper.m_RemoteBombActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Detonate.started += instance.OnDetonate;
                @Detonate.performed += instance.OnDetonate;
                @Detonate.canceled += instance.OnDetonate;
            }
        }
    }
    public RemoteBombActions @RemoteBomb => new RemoteBombActions(this);
    public interface IRemoteBombActions
    {
        void OnDetonate(InputAction.CallbackContext context);
    }
}
