//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/UIDisableInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIDisableInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIDisableInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIDisableInputs"",
    ""maps"": [
        {
            ""name"": ""AttachmentTable"",
            ""id"": ""1088b5a9-c6ec-4f7e-816f-2cdf07c1c177"",
            ""actions"": [
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""842be4de-e249-44a3-b446-ed486456420c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""62b316d3-55e0-4b40-a299-f1579212e824"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // AttachmentTable
        m_AttachmentTable = asset.FindActionMap("AttachmentTable", throwIfNotFound: true);
        m_AttachmentTable_Escape = m_AttachmentTable.FindAction("Escape", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AttachmentTable
    private readonly InputActionMap m_AttachmentTable;
    private IAttachmentTableActions m_AttachmentTableActionsCallbackInterface;
    private readonly InputAction m_AttachmentTable_Escape;
    public struct AttachmentTableActions
    {
        private @UIDisableInputs m_Wrapper;
        public AttachmentTableActions(@UIDisableInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Escape => m_Wrapper.m_AttachmentTable_Escape;
        public InputActionMap Get() { return m_Wrapper.m_AttachmentTable; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AttachmentTableActions set) { return set.Get(); }
        public void SetCallbacks(IAttachmentTableActions instance)
        {
            if (m_Wrapper.m_AttachmentTableActionsCallbackInterface != null)
            {
                @Escape.started -= m_Wrapper.m_AttachmentTableActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_AttachmentTableActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_AttachmentTableActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_AttachmentTableActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public AttachmentTableActions @AttachmentTable => new AttachmentTableActions(this);
    public interface IAttachmentTableActions
    {
        void OnEscape(InputAction.CallbackContext context);
    }
}
