//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/UIItemWeaponInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIItemWeaponInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIItemWeaponInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIItemWeaponInputs"",
    ""maps"": [
        {
            ""name"": ""Both"",
            ""id"": ""26cdc36a-3323-4c6b-a5c0-ded154764292"",
            ""actions"": [
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""e5ca6e91-a18c-40ca-980d-9e55ab603a75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""40d1d843-015b-46bd-9f3d-ca76400ab49d"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Item"",
            ""id"": ""260acac2-3e67-410f-9143-aecb093bc71a"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""80318694-a1e1-4f1a-b0ce-2dbbd9c27915"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9b005b49-0706-4e42-8d9e-b38fbd918e71"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Weapon"",
            ""id"": ""6afbf33d-9d38-483f-9998-820842882aa8"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""dbde0168-167f-47bd-88c1-a99f33254370"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8202d773-b0c2-4ede-ab29-f1f0605bdd7a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Both
        m_Both = asset.FindActionMap("Both", throwIfNotFound: true);
        m_Both_Drop = m_Both.FindAction("Drop", throwIfNotFound: true);
        // Item
        m_Item = asset.FindActionMap("Item", throwIfNotFound: true);
        m_Item_Newaction = m_Item.FindAction("New action", throwIfNotFound: true);
        // Weapon
        m_Weapon = asset.FindActionMap("Weapon", throwIfNotFound: true);
        m_Weapon_Newaction = m_Weapon.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Both
    private readonly InputActionMap m_Both;
    private IBothActions m_BothActionsCallbackInterface;
    private readonly InputAction m_Both_Drop;
    public struct BothActions
    {
        private @UIItemWeaponInputs m_Wrapper;
        public BothActions(@UIItemWeaponInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Drop => m_Wrapper.m_Both_Drop;
        public InputActionMap Get() { return m_Wrapper.m_Both; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BothActions set) { return set.Get(); }
        public void SetCallbacks(IBothActions instance)
        {
            if (m_Wrapper.m_BothActionsCallbackInterface != null)
            {
                @Drop.started -= m_Wrapper.m_BothActionsCallbackInterface.OnDrop;
                @Drop.performed -= m_Wrapper.m_BothActionsCallbackInterface.OnDrop;
                @Drop.canceled -= m_Wrapper.m_BothActionsCallbackInterface.OnDrop;
            }
            m_Wrapper.m_BothActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Drop.started += instance.OnDrop;
                @Drop.performed += instance.OnDrop;
                @Drop.canceled += instance.OnDrop;
            }
        }
    }
    public BothActions @Both => new BothActions(this);

    // Item
    private readonly InputActionMap m_Item;
    private IItemActions m_ItemActionsCallbackInterface;
    private readonly InputAction m_Item_Newaction;
    public struct ItemActions
    {
        private @UIItemWeaponInputs m_Wrapper;
        public ItemActions(@UIItemWeaponInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Item_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Item; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ItemActions set) { return set.Get(); }
        public void SetCallbacks(IItemActions instance)
        {
            if (m_Wrapper.m_ItemActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_ItemActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_ItemActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_ItemActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_ItemActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public ItemActions @Item => new ItemActions(this);

    // Weapon
    private readonly InputActionMap m_Weapon;
    private IWeaponActions m_WeaponActionsCallbackInterface;
    private readonly InputAction m_Weapon_Newaction;
    public struct WeaponActions
    {
        private @UIItemWeaponInputs m_Wrapper;
        public WeaponActions(@UIItemWeaponInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_Weapon_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_Weapon; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WeaponActions set) { return set.Get(); }
        public void SetCallbacks(IWeaponActions instance)
        {
            if (m_Wrapper.m_WeaponActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_WeaponActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_WeaponActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_WeaponActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_WeaponActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public WeaponActions @Weapon => new WeaponActions(this);
    public interface IBothActions
    {
        void OnDrop(InputAction.CallbackContext context);
    }
    public interface IItemActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
    public interface IWeaponActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
